import "./globals.css";
import { Inter, Lato, Montserrat, Open_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"], display: "swap" });

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});
const lato = Lato({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
});

const open = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${montserrat.variable} ${open.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
